### ISSUE TITLE
[maintainer] anblave & xmartinezpujol

### ISSUE THREAD

**Issue by anblave** [gatsbyjs/gatsby-es#101]
Razones:
- Puedo ayudar revisando ortografía y gramática con español neutro, además de errores humanos.
- Puedo hacer una primera revisión de la traducción.

PR's
https://github.com/pulls?q=is%3Apr+author%3Aanblave+archived%3Afalse+is%3Aclosed

UPDATE:
tambien nomino a @xmartinezpujol. ha estado ayudando revisando y taggeando PRs. :)

**Comment by horacioh** [comment]
Que les parece @Darking360 @nucliweb @gusma ?

por mi OK!

**Comment by gusma** [comment]
Por mi Ok! @horacioh

**Comment by nucliweb** [comment]
Me parece genial! @horacioh

**Comment by horacioh** [comment]
done! ➡️ #104 

cuando puedan @nucliweb @Darking360 :)

**Comment by nucliweb** [comment]
Done!
Welcome @gusma  & @xmartinezpujol
