### ISSUE TITLE
Biblioteca -> Librería

### ISSUE THREAD

**Issue by horacioh** [gatsbyjs/gatsby-es#105]
me suena mejor Librería que Biblioteca...

que les parece @gusma @Darking360 @nucliweb @xmartinezpujol ???

yo me encargaría de cambiar todas las traducciones actuales...

**Comment by xmartinezpujol** [comment]
Por mi bien, aunque tampoco habría mucho problema ya que ambas opciones son correctas en software al no ser la habitual traducción literal que usamos en el caso de las tiendas de libros.

**Fuente**: https://es.wikipedia.org/wiki/Biblioteca_(inform%C3%A1tica)#Nota_terminol%C3%B3gica

**Comment by horacioh** [comment]
a ver que dicen los demás! :)

**Comment by gusma** [comment]
Yo estoy a favor de dejarlo en librería, pero se de quienes prefieren biblioteca.

**Comment by nucliweb** [comment]
También voto por librería 😊

**Comment by horacioh** [comment]
entonces lo cambio!!

ya lo hago mañana :)
