### ISSUE TITLE
Spanish Translation Progress

### ISSUE THREAD

**Issue by horacioh** [gatsbyjs/gatsby-es#4]
# 🚨 Please Read this before contributing 🚨

## Maintainer List
@Darking360
@horacioh
@nucliweb 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below. Do not create new issues claiming for new work please, let's keep everything here. If you already have an issue opened, please close it after your PR gets merged 🎉. Thanks!
2. Comment below with the name of the page you would like to translate. Take only one page at a time.
3. Submit a PR, assign @horacioh or @Darking360 and add a link to it to your comment!

Please check the style guide (soon!) to make sure translations are written in a consistent manner.

## Work List

- 🏃 Work in Progress
- 👀 In Review
- 🎉 Done

## Core Pages

To do before releasing as an "official" translation. Please translate these pages first.

### Pages

- [ ] Home Page (@RockLee444) 🏃‍♂️
(TBD...)

### docs

- [x] accessibility-statement.md (@xmartinezpujol) 🎉

### docs/tutorials

- [x] blog-netlify-cms-tutorial (@xmartinezpujol) 🎉
- [ ] ecommerce-tutorial (@nacapulque) 🏃‍♂️
- [ ] gatsby-image-tutorial (@JuanJavier1979) 🏃‍♂️
- [x] part-zero (@horacioh)
- [x] part-one (@Darking360)
- [x] part-two (https://github.com/anblave)
- [ ] part-three (@hielfx) 🏃
- [ ] part-four (@rubenLozanoMar) 🏃‍♂️
- [ ] part-five (@jackbravo)
- [ ] part-six (@jatempa) 🏃
- [ ] part-seven (@jatempa) 🏃‍♂️
- [x] part-eight (https://github.com/anblave)
- [x] additional-tutorials.md
- [x] authentication-tutorial.md (@MeLlamoPablo) 🏃‍♂️
- [ ] building-a-theme.md
- [x] index.md (@horacioh)
- [ ] prismic-source-graphql-tutorial.md
- [ ] theme-tutorials.md (@tairosonloa) 🏃‍♂️
- [ ] using-a-theme.md (@tairosonloa) 🏃‍♂️
- [x] using-multiple-themes-together.md (@MdHanif01) 🎉 
- [x] wordpress-image-tutorial.md (@jorgeepc) 🏃‍♂️
- [ ] wordpress-source-plugin-tutorial.md
- [x] writing-documentation-with-docz.md

### docs/contributing

- [ ] blog-and-website-contributions.md (@piraces) 🏃
- [ ] code-contributions.md (@xmartinezpujol) 👀
- [ ] code-of-conduct.md (@hielfx) 🏃‍♂️
- [ ] community-contributions.md (@s-Hale) 👀
- [ ] community.md (@kbravh) 🏃
- [ ] contributor-swag.md (@jose4125) 👀
- [ ] docs-contributions.md (@jorgeruvalcaba) 🏃‍♂️
- [ ] docs-templates.md
- [ ] gatsby-governance-model.md
- [ ] gatsby-style-guide.md
- [x] how-to-contribute.md (@s-Hale) 🎉
- [ ] how-to-file-an-issue.md (@jose4125) 👀
- [ ] how-to-label-an-issue.md
- [ ] how-to-make-a-reproducible-test-case.md
- [x] how-to-open-a-pull-request.md (@gusma) 👀
- [ ] how-to-pitch-gatsby.md
- [ ] how-to-run-a-gatsby-workshop.md (@gusma) 👀
- [ ] how-to-write-a-stub.md (@kbravh) 🏃‍♂️
- [ ] managing-pull-requests.md
- [ ] organize-a-gatsby-event.md (@imagentleman) 🏃‍♂️
- [ ] pair-programming.md
- [ ] rfc-process.md
- [ ] setting-up-your-local-dev-environment.md (@jose4125) 🏃‍♂️
- [ ] site-showcase-submissions.md (@m1guelpf) 🏃‍♂️
- [ ] submit-to-creator-showcase.md
- [ ] submit-to-plugin-library.md (@xmartinezpujol) 🏃‍♂️
- [ ] submit-to-starter-library.md
- [ ] triaging-github-issues.md
- [ ] using-an-online-dev-environment.md (@rodrigobustamante) 🏃‍♂️
- [x] where-to-participate.md (@gusma) 🏃‍♂️
- [x] why-contribute-to-gatsby.md (@jose4125) 🎉

### docs/docs

- [x] add-404-page.md (@piraces) 🎉
- [ ] add-a-manifest-file.md (@piraces) 🏃‍♂️
- [ ] add-a-service-worker.md (@alvaromontoro) ✍️ 
- [ ] add-custom-webpack-config.md (@alvaromontoro) 🏃‍♂️
- [ ] add-offline-support-with-a-service-worker.md (@elpuas) 🏃‍♂️
- [x] add-page-metadata.md (@rodrigobustamante) 🏃‍♂️
- [ ] add-seo-component.md
- [ ] adding-a-list-of-markdown-blog-posts.md
- [ ] adding-an-rss-feed.md (@rodrigobustamante) 🏃‍♂️
- [ ] adding-analytics.md (@rubenLozanoMar) 🏃‍♂️
- [x] adding-comments.md (@meyruiz) 🏃‍♂️
- [ ] adding-forms.md
- [ ] adding-markdown-pages.md
- [ ] adding-page-transitions-with-plugin-transition-link.md
- [ ] adding-page-transitions.md
- [ ] adding-pagination.md
- [ ] adding-search-with-algolia.md
- [ ] adding-search-with-elasticlunr.md
- [ ] adding-search-with-js-search.md
- [ ] adding-search.md (@rubenLozanoMar) 🏃‍♂️
- [ ] adding-tags-and-categories-to-blog-posts.md
- [ ] adding-website-functionality.md
- [ ] answering-it-security.md
- [ ] api-proxy.md
- [ ] api-reference.md
- [ ] api-specification.md
- [ ] asset-prefix.md
- [ ] audit-with-lighthouse.md
- [ ] awesome-gatsby.md
- [ ] babel-plugin-macros.md
- [ ] babel.md (@EduardoGHdez) 🏃
- [ ] basic-hardware-software-requirements.md
- [ ] best-practices-for-orgs.md
- [ ] browser-support.md
- [ ] build-caching.md (@nicodelpiano) 🏃‍♂️
- [ ] building-a-blog.md
- [ ] building-a-contact-form.md
- [ ] building-a-portfolio.md
- [ ] building-a-site-with-asynchronous-data.md
- [ ] building-a-site-with-authentication.md
- [ ] building-an-e-commerce-site.md
- [ ] building-an-image-heavy-site.md
- [ ] building-apps-with-gatsby.md
- [ ] building-with-components.md
- [ ] bulma.md (@blackfile) ✍️ 
- [ ] caching.md
- [ ] centralizing-your-sites-navigation.md
- [ ] cheat-sheet.md
- [ ] client-data-fetching.md
- [ ] client-only-routes-and-user-authentication.md
- [ ] coming-from-react-to-gatsby.md
- [ ] component-libraries.md
- [ ] conceptual-guide.md
- [ ] configuring-ca-certificates.md
- [ ] content-and-data.md
- [ ] convincing-others.md (@gusma) 🏃
- [ ] creating-a-local-plugin.md
- [x] creating-a-sitemap.md (@SerotoninaAbad) 🏃‍♂️
- [ ] creating-a-source-plugin.md
- [ ] creating-a-starter.md
- [ ] creating-a-transformer-plugin.md
- [ ] creating-and-modifying-pages.md
- [ ] creating-global-styles.md
- [ ] creating-plugins.md
- [ ] creating-prefixed-404-pages-for-different-languages.md
- [ ] creating-slugs-for-pages.md
- [x] css-in-js.md (@zombispormedio) 🎉
- [ ] css-libraries-and-frameworks.md (@s-Hale) 👀
- [ ] css-modules.md
- [ ] custom-html.md (@Nievac) 🏃‍♂️
- [ ] customization.md
- [ ] data-storage-redux.md
- [ ] debugging-async-lifecycles.md
- [ ] debugging-cache-issues.md
- [ ] debugging-html-builds.md
- [ ] debugging-replace-renderer-api.md
- [ ] debugging-the-build-process.md
- [ ] debugging.md (@ghost) 🏃‍♂️
- [ ] deploying-and-hosting.md
- [ ] deploying-to-aerobatic.md
- [ ] deploying-to-aws-amplify.md
- [ ] deploying-to-gitlab-pages.md
- [ ] deploying-to-heroku.md
- [ ] deploying-to-netlify.md
- [ ] deploying-to-render.md
- [ ] deploying-to-s3-cloudfront.md
- [ ] deploying-to-surge.md
- [ ] deploying-to-zeit-now.md
- [ ] different-organization-types.md
- [ ] emotion.md (@zombispormedio) 🏃
- [ ] end-to-end-testing.md
- [ ] environment-variables.md
- [ ] eslint.md (@JanLawrence) ✍️ 
- [ ] faster-recruiting.md (@gusma) 🏃‍♂️
- [ ] files-gatsby-looks-for-in-a-plugin.md
- [ ] first-professional-project.md
- [ ] gatsby-agency-partnership.md
- [ ] gatsby-cli.md
- [ ] gatsby-config.md
- [ ] gatsby-core-philosophy.md
- [ ] gatsby-for-agencies.md
- [ ] gatsby-for-companies.md
- [ ] gatsby-for-freelancers.md
- [ ] gatsby-image.md
- [ ] gatsby-in-the-enterprise.md
- [ ] gatsby-internals-terminology.md
- [ ] gatsby-internals.md
- [ ] gatsby-lifecycle-apis.md
- [ ] gatsby-link.md
- [ ] gatsby-on-linux.md
- [ ] gatsby-on-windows.md
- [ ] gatsby-project-structure.md
- [ ] gatsby-repl.md
- [ ] gatsby-source-filesystem-programmatic-import.md
- [ ] gatsby-vendor-partnership.md
- [ ] glamor.md
- [ ] global-css.md (@rubenLozanoMar) 🏃‍♂️
- [ ] glossary.md
- [ ] going-gatsby-only.md
- [ ] graphql-api.md
- [ ] graphql-concepts.md
- [ ] graphql-reference.md
- [ ] graphql.md (@EduardoGHdez) 🏃‍♂️
- [ ] guides.md
- [ ] headless-cms.md
- [ ] how-code-splitting-works.md
- [ ] how-gatsby-boosts-career.md
- [ ] how-gatsby-works-with-github-pages.md
- [ ] how-plugins-apis-are-run.md
- [ ] how-shadowing-works.md
- [ ] how-to-add-a-list-of-markdown-blog-posts.md
- [ ] html-generation.md
- [ ] images-and-files.md
- [ ] importing-assets-into-files.md
- [ ] importing-media-content.md
- [ ] interactive-pages.md
- [ ] internal-data-bridge.md
- [ ] layout-components.md
- [ ] life-and-times-of-a-gatsby-build.md
- [ ] linking-and-prefetching-with-gatsby.md
- [ ] linking-between-pages.md
- [ ] loading-plugins-from-your-local-plugins-folder.md
- [ ] local-https.md
- [ ] localization-i18n.md
- [ ] lower-bids-more-profit.md
- [ ] maintaining-a-plugin.md
- [ ] making-components-discoverable.md
- [ ] making-your-site-accessible.md
- [ ] migrating-from-v0-to-v1.md
- [ ] migrating-from-v1-to-v2.md
- [ ] multi-core-builds.md
- [ ] naming-a-plugin.md
- [ ] node-creation.md
- [ ] node-interface.md
- [ ] node-tracking.md
- [ ] optimizing-site-performance-with-guessjs.md
- [ ] overview.md
- [ ] page-creation.md
- [ ] page-node-dependencies.md
- [ ] page-query.md
- [ ] partnering-with-gatsby.md
- [ ] path-prefix.md
- [ ] performance-tracing.md
- [ ] performance.md
- [ ] pixabay-source-plugin-tutorial.md
- [ ] plugins.md
- [ ] porting-from-create-react-app-to-gatsby.md
- [ ] porting-to-gatsby.md
- [ ] post-css.md
- [ ] preoptimizing-images.md
- [ ] preparing-for-deployment.md
- [ ] preparing-for-site-launch.md
- [ ] preparing-your-environment.md
- [ ] production-app.md
- [ ] programmatically-create-pages-from-data.md
- [ ] progressive-web-app.md
- [ ] prpl-pattern.md
- [ ] query-behind-the-scenes.md
- [ ] query-execution.md
- [ ] query-extraction.md
- [ ] quick-start.md
- [ ] reach-router-and-gatsby.md
- [ ] recipes.md
- [ ] releases-and-migration.md
- [ ] remark-plugin-tutorial.md
- [ ] rendering-sidebar-navigation-dynamically.md
- [ ] resource-handling-and-service-workers.md
- [ ] routing.md
- [ ] running-queries-with-graphiql.md
- [ ] sanitize-your-stack.md
- [ ] sass.md
- [ ] scaling-issues.md
- [ ] schema-connections.md
- [ ] schema-customization.md
- [ ] schema-generation.md
- [ ] schema-gql-type.md
- [ ] schema-input-gql.md
- [ ] schema-sift.md
- [ ] security-in-gatsby.md
- [ ] seo.md (@enBonnet) 🏃
- [ ] setting-up-gatsby-without-gatsby-new.md
- [ ] sharing-components-across-websites.md
- [ ] sourcing-content-from-json-or-yaml.md
- [ ] sourcing-from-agilitycms.md
- [ ] sourcing-from-buttercms.md
- [ ] sourcing-from-contentful.md
- [ ] sourcing-from-contentstack.md
- [ ] sourcing-from-databases.md
- [ ] sourcing-from-drupal.md
- [ ] sourcing-from-ghost.md
- [ ] sourcing-from-graphcms.md
- [ ] sourcing-from-hosted-services.md
- [ ] sourcing-from-kentico-cloud.md
- [ ] sourcing-from-netlify-cms.md
- [ ] sourcing-from-prismic.md
- [ ] sourcing-from-private-apis.md
- [ ] sourcing-from-prose.md
- [ ] sourcing-from-sanity.md
- [ ] sourcing-from-the-filesystem.md
- [ ] sourcing-from-wordpress.md
- [ ] starters.md
- [ ] static-folder.md
- [ ] static-query.md
- [ ] static-vs-normal-queries.md
- [ ] styled-components.md (@zombispormedio) 🏃‍♂️
- [ ] styling.md
- [ ] tailwind-css.md
- [ ] telemetry.md
- [ ] testing-components-with-graphql.md
- [ ] testing-css-in-js.md
- [ ] testing-react-components.md
- [ ] testing.md
- [ ] theme-api.md
- [ ] theme-ui.md
- [ ] themes.md (@imagentleman) 🏃‍♂️
- [ ] thinking-in-gatsby.md
- [ ] third-party-graphql.md
- [ ] typography-js.md (@Nievac) 🏃‍♂️
- [ ] unit-testing.md
- [ ] upgrade-gatsby-and-dependencies.md (@urielhdz) 🏃‍♂️
- [ ] upgrading-node-js.md (@gusma) 🏃‍♂️
- [ ] use-static-query.md
- [ ] using-a-plugin-in-your-site.md
- [ ] using-client-side-only-packages.md
- [ ] using-fragments.md (@jclopezdev) 🏃‍♂️
- [ ] using-gatsby-image.md
- [ ] using-gatsby-professionally.md
- [ ] using-gatsby-without-graphql.md
- [ ] using-graphql-playground.md
- [ ] v1-release-notes.md
- [ ] v2-release-notes.md
- [ ] visual-testing-with-storybook.md (@gusma) 🏃‍♂️
- [ ] webpack-and-ssr.md
- [ ] what-is-a-plugin.md
- [ ] what-you-dont-need-plugins-for.md
- [ ] why-gatsby-uses-graphql.md
- [ ] winning-over-clients.md
- [ ] winning-over-developers.md
- [ ] winning-over-engineering-leaders.md
- [ ] winning-over-executives.md
- [ ] winning-over-marketers.md
- [ ] winning-over-stakeholders.md
- [ ] working-with-gifs.md (@gusma) 🏃‍♂️
- [ ] working-with-images-in-markdown.md
- [ ] working-with-images.md
- [ ] working-with-video.md
- [ ] write-pages.m

### docs/docs/themes

- [ ] building-themes.md (@enBonnet) 🏃‍♂️
- [ ] conventions.md
- [ ] converting-a-starter.md
- [ ] shadowing.md
- [ ] theme-composition.md
- [ ] using-a-gatsby-theme.md
- [ ] using-multiple-gatsby-themes.md (@JanLawrence) 🎉
- [ ] what-are-gatsby-themes.md

### docs/docs/mdx

- [ ] customizing-components.md
- [ ] getting-started.md (@jmay4826) ✍️ 
- [ ] index.md
- [ ] markdown-syntax.md
- [ ] plugins.md (@JanLawrence) 🏃
- [ ] programmatically-creating-pages.md
- [ ] writing-pages.m

**Comment by s-Hale** [comment]
Can I take 'community-contributions'? thanks.

**Comment by jose4125** [comment]
I can take 'how-to-file-an-issue.md', thanks

**Comment by Darking360** [comment]
@s-Hale @jose4125 Hey! Thank you for jumping in, you have those assigned to you 🚀 We're still working on the glossary of terms and the style guide for this, but you can start translating and we can check in the PR how it went, try to use neutral Spanish and don't add or remove lines from the document 👍 Thanks! 🎖

**Comment by s-Hale** [comment]
@Darking360 Apologies, I meant to create a branch for the new PR but have accidentally pushed it up to the old one (it now contains 3). Would it be best, going forward, to create a branch for each article?

**Comment by Darking360** [comment]
@s-Hale No problem, the idea would be to have one PR per page, because it's easier to prioritize and to review one by one, but it's ok since it's the beginning, just make sure to open separate ones in the future 💪

**Comment by jose4125** [comment]
I'm going to take another one :),  why-contribute-to-gatsby.md

**Comment by horacioh** [comment]
you got it @jose4125 ! :)

**Comment by YzahFe** [comment]
Can I take 'how-to-label-an-issue'? Thank you

**Comment by horacioh** [comment]
done @YzahFe! :)

**Comment by YzahFe** [comment]
Can I take another one?  'how-to-pitch-gatsby.md'

**Comment by YzahFe** [comment]
> Can I take another one? 'how-to-pitch-gatsby.md'

I'm done with the first one  'how-to-label-an-issue'

**Comment by Darking360** [comment]
@YzahFe You got them 🚀

**Comment by jose4125** [comment]
I'm going to take contributor-swag.md

**Comment by Darking360** [comment]
Sure, go for it @jose4125 💪

**Comment by gusma** [comment]
Can I take how-to-open-a-pull-request.md? Thanks!

**Comment by horacioh** [comment]
go for it @gusma!!

**Comment by YzahFe** [comment]
I'm going to take pair-programming.md. Thank you

**Comment by gusma** [comment]
Also will be taking on where-to-participate.md if that's ok with you.

**Comment by JanLawrence** [comment]
Hi can I take 'eslint.md'? Thank you

**Comment by horacioh** [comment]
@YzahFe @gusma @JanLawrence there you go! 👍

**Comment by YzahFe** [comment]
I'll going to take 'docs/docs/mdx/index.md'

**Comment by imagentleman** [comment]
I'd like to take organize-a-gatsby-event.md

**Comment by Darking360** [comment]
@YzahFe @imagentleman You got them! Please remember to only pick one at a time :muscle:

**Comment by YzahFe** [comment]
Hi I've already translated pair-programming.md & docs/docs/mdx/index.md yesterday, can I take docs/docs/themes/what-are-gatsby-themes.md ?

Thank you

**Comment by jmay4826** [comment]
Could I take docs/docs/mdx/getting-started.md?

**Comment by gusma** [comment]
I'll be taking on  how-to-run-a-gatsby-workshop.md if that's ok with you.

**Comment by Darking360** [comment]
@YzahFe @jmay4826 @gusma Greetings! You have them, go for it :fire:

**Comment by zombispormedio** [comment]
I would be interested to translate stuff about CSS-in-JS (emotion, styled-components, theme-ui). Could I start with `docs/css-in-js.md`?

**Comment by xmartinezpujol** [comment]
Hi there! 👋 

Can I take `docs/accessibility-statement.md` ?

**Comment by dosden** [comment]
Hello, can I get docs/docs/themes/theme-composition.md? Thanks

**Comment by JanLawrence** [comment]
Hi, can i take using-multiple-gatsby-themes.md? Thank you

**Comment by horacioh** [comment]
@JanLawrence @dosden @xmartinezpujol @zombispormedio you all are set! :)

**Comment by piraces** [comment]
Hi, can I get docs/docs/add-404-page.md ? Thank you.

**Comment by Nievac** [comment]
Hi, can I take ```docs/docs/custom-html.md```?

**Comment by xmartinezpujol** [comment]
I will work on `docs/tutorials/blog-netlify-cms-tutorial`

**Comment by JanLawrence** [comment]
Hi, I just finished translating `docs/docs/themes/using-multiple-gatsby-themes.md`, can I take another file `docs/docs/mdx/plugins.md`?

**Comment by Darking360** [comment]
@JanLawrence @xmartinezpujol You got them! Go for it 💪

**Comment by jose4125** [comment]
I'm going to take setting-up-your-local-dev-environment.md

**Comment by Darking360** [comment]
@jose4125 Go for it 🚗

**Comment by piraces** [comment]
I'm going to take docs/docs/add-a-manifest-file.md 😃

**Comment by Darking360** [comment]
@piraces You got it 🤘

**Comment by Nievac** [comment]
Hi, I am done with ```docs/docs/custom-html.md```.

Can I take ```docs/docs/typography-js.md```?

**Comment by alvaromontoro** [comment]
Hi! Can I get `add-a-service-worker.md`?

**Comment by Darking360** [comment]
Greetings @alvaromontoro @Nievac You got them, feel free to start those 🚀

**Comment by MdHanif01** [comment]
Can i take theme-tutorials.md ?

**Comment by piraces** [comment]
Can i take docs/contributing/blog-and-website-contributions.md ? Thanks.

**Comment by horacioh** [comment]
@MdHanif01 @piraces go for it!!

**Comment by hielfx** [comment]
can I take tutorial part-three

**Comment by zombispormedio** [comment]
can I take ```docs/emotion.md```?

**Comment by m1guelpf** [comment]
can I take `site-showcase-submissions.md`?

**Comment by kbravh** [comment]
I can start off with contributing/how-to-write-a-stub.md!

**Comment by gusma** [comment]
I'll be starting off faster-recruiting.md if that's ok with you.

**Comment by alvaromontoro** [comment]
Can I start `add-custom-webpack-config.md` while waiting for the approval of the other one?

**Comment by Darking360** [comment]
Hey, people @hielfx @zombispormedio @m1guelpf @kbravh @gusma @alvaromontoro You got them, sorry for the delay on reviews we were working on some official documentation on how to get started with the translations, go for it and really thank you! :rocket: :pray:

**Comment by MdHanif01** [comment]
Hi I am done with theme-tutorials.md

Can i get using-multiple-themes-together.md

**Comment by MdHanif01** [comment]
Translated Theme-Tutorials.md [#41 ](url)

**Comment by kbravh** [comment]
I've wrapped up contributing/how-to-write-a-stub.md #42 .
I can pick up contributing/community.md.

**Comment by MdHanif01** [comment]
Translated Theme-Tutorials.md  #41

**Comment by horacioh** [comment]
@kbravh @MdHanif01 go for it!!

sorry about the delay on reviews! 🙏 
you all are AWESOME and there are a lot of translations going on lately! :)

thanks again and hopefully we will keep up soon! ;)

**Comment by elpuas** [comment]
can I start with `add-offline-support-with-a-service-worker.md`

**Comment by kbravh** [comment]
I've finished up community.md! #43

**Comment by dosden** [comment]
Hi I'm going to take 'docs/docs/add-a-manifest-file.md'

Thank you

**Comment by dosden** [comment]
Hi I'm going to take 'add-page-metadata.md'

Thank you

**Comment by nicodelpiano** [comment]
Hi! I'm going to take `build-caching.md`!

Thanks!

**Comment by urielhdz** [comment]
Hey! I would like to take the `upgrade-gatsby-and-dependencies.md` reference guide :)

**Comment by gusma** [comment]
I'll be taking on  working-with-gifs.md if that's ok.

**Comment by gusma** [comment]
Done with `working-with-gifs.md`. #47

**Comment by hielfx** [comment]
@horacioh @Darking360 done with https://github.com/gatsbyjs/gatsby-es/pull/48

**Comment by MdHanif01** [comment]
Done with #49

**Comment by MdHanif01** [comment]
Can i take conceptual-guide.md ?

Done with #49

**Comment by xmartinezpujol** [comment]
#36 ready to go  🚀 
Can I take `docs/contributing/code-contributions.md` ?

**Comment by horacioh** [comment]
@elpuas @urielhdz @nicodelpiano @dosden @urielhdz @MdHanif01 @gusma 
you are all set!!

PLEASE!! WE NEED HELP! 🙏 
if some of you are willing to curate content, please reach us via the GatsbyJS Discord channel to either @Darking360 or myself (there's a special channel for the spanish translations)

we are only two people, with fulltime jobs and you all are great and we are not keeping up with all your amazing work!

We (and the community) will appreciate your effort and time!
thanks!

**Comment by MdHanif01** [comment]
@horacioh @Darking360 
Can i take Debugging.md ?

Done with #52

**Comment by rubenLozanoMar** [comment]
Can I do part-four?

**Comment by nacapulque** [comment]
can I take ecommerce-tutorial?

thanks!

**Comment by hielfx** [comment]
Can I take `code-of-conduct.md`?

**Comment by WerikG** [comment]
@horacioh @Darking360 
Can i take  docs/docs  reach-router-and-gatsby.md ?

**Comment by meyruiz** [comment]
@horacioh @Darking360 
Can I take docs/docs adding-comments.md ?

**Comment by alvaromontoro** [comment]
I wrapped `add-custom-webpack-config.md` in #54 

Can I take `add-seo-component.md`?

**Comment by jorgeruvalcaba** [comment]
@horacioh @Darking360 can I take `ecommerce-tutorial`?

**Comment by xmartinezpujol** [comment]
> PLEASE!! WE NEED HELP! 🙏
> if some of you are willing to curate content, please reach us via the GatsbyJS Discord channel to either @Darking360 or myself (there's a special channel for the spanish translations)
> 
> we are only two people, with fulltime jobs and you all are great and we are not keeping up with all your amazing work!
> 
> We (and the community) will appreciate your effort and time!
> thanks!

I'll be glad to help, I will contact you in a few days.
I plan to be in the GatsbyJS community for a while as I will be using it for freelance projects. 
For that reason I will be more than happy to keep contributing to help the community grow  🚀. 

Good work everyone! 👏

**Comment by EduardoGHdez** [comment]
Can I take `babel.md`?

**Comment by jatempa** [comment]
Can I take docs/tutorials **part three**?

**Comment by enBonnet** [comment]
Can i take `seo.md` ? @horacioh @Darking360 if it's done, could you tell me wich one?

**Comment by imagentleman** [comment]
I'd like to take themes.md

**Comment by rodrigobustamante** [comment]
Can i take `using-an-online-dev-environment.md`? @horacioh @Darking360

**Comment by gusma** [comment]
I'll be taking `visual-testing-with-storybook.md` if that's ok with everyone.

**Comment by RockLee444** [comment]
Can I take "Home Page"? Thank you!

**Comment by EduardoGHdez** [comment]
I'll take `graphql.md` 🙌

**Comment by JuanJavier1979** [comment]
Can I take gatsby-image-tutorial? @horacioh @Darking360

**Comment by zombispormedio** [comment]
can I take docs/styled-components.md?

**Comment by MdHanif01** [comment]
Hey there @horacioh @Darking360 

Can i take Debugging.md ?

already done with #52

**Comment by gusma** [comment]
Undertook convincing-others.md. #69

**Comment by ClauVex** [comment]
Greetings @horacioh @Darking360 :)
I would like to translate building-themes.md 
Thanks!

**Comment by tairosonloa** [comment]
I'll help a little too. I use Gatsby a lot and documentation is one of the pillars of free software. I'll start with `docs/tutorial/using-a-theme.md` and I'll update this comment later if I pick another one when finished.

Contributing:
- `docs/tutorial/using-a-theme.md`  (in progress)

**Comment by rodrigobustamante** [comment]
I can translate `docs/docs/adding-an-rss-feed.md` file!

**Comment by gusma** [comment]
I'll be undertaking `docs/docs/upgrading-node-js.md`.

**Comment by jatempa** [comment]
Done #71

**Comment by jatempa** [comment]
May I translate part-four?  @horacioh o @Darking360

**Comment by enBonnet** [comment]
Puedo traducir building-themes.md ? @horacioh o @Darking360

**Comment by rodrigobustamante** [comment]
#67 and #72 ready for review!

**Comment by rubenLozanoMar** [comment]
#78 Ready for review.
- docs/tutorial/part-four/index.md
- docs/docs/global-css.md
- docs/docs/adding-analytics.md
- docs/docs/adding-search.md

**Comment by xmartinezpujol** [comment]
#84 ready to review :eyes:

Can I take `docs/contributing/submit-to-plugin-library`?

**Comment by jclopezdev** [comment]
Can I take 'docs/docs/using-fragments.md'? thanks.

**Comment by horacioh** [comment]
@jclopezdev @xmartinezpujol @rubenLozanoMar @ClauVex @ghost @zombispormedio @JuanJavier1979 @EduardoGHdez @RockLee444 @imagentleman @Nievac @hielfx @nacapulque you are all assigned!!

@enBonnet tienes asignado `seo.md`, no `building-themes` :)

**Comment by jatempa** [comment]
May I take part-seven @horacioh ?

**Comment by jatempa** [comment]
> @jclopezdev @xmartinezpujol @rubenLozanoMar @ClauVex @ghost @zombispormedio @JuanJavier1979 @EduardoGHdez @RockLee444 @imagentleman @Nievac @hielfx @nacapulque you are all assigned!!
> 
> @enBonnet tienes asignado `seo.md`, no `building-themes` :)
> @jatempa sorry `part-four` was already taken :(

May I take part-seven @horacioh ?

**Comment by jatempa** [comment]
May I take part-seven @horacioh ?

**Comment by horacioh** [comment]
@jatempa part seven is yours! :)

**Comment by horacioh** [comment]
## FOR THE RECORD

we are doing our best to keep up with all your amazing work! remember that we all have our fulltime jobs too :)

before you start translating:
- **MAKE SURE WE ASSIGN THE DOC TO YOU**
- we do add a reaction to you comment when that's official (🚀 👍 or something positive)
- ** CREATE ONE SINGLE PR PER FILE**: this help us to keep each file isolated and selfcontained.

apart from this, **YOU ALL ARE AWESOME** thanks again for all your amazing work on behalf of the Gatsby Core team and all the Maintainers @Darking360 @nucliweb and myself!

more maintainers coming soon!!

**Comment by jorgeruvalcaba** [comment]
@horacioh can I take `docs-contributions.md`?

**Comment by horacioh** [comment]
@jorgeruvalcaba all yours! ;)

**Comment by jorgeepc** [comment]
Can I take docs/tutorials/wordpress-image-tutorial.md? Thanks. @horacioh @Darking360

**Comment by SerotoninaAbad** [comment]
May I take `docs/docs/creating-a-sitemap.md`? @horacioh @Darking360

**Comment by RockLee444** [comment]
@horacioh @Darking360 Hey! Do you know where can I find the Home Page file? I couldn't find it. 
Thank you!

**Comment by meyruiz** [comment]
Can I take docs/docs adding-comments.md ? @horacioh

**Comment by rodrigobustamante** [comment]
Can i take  add-page-metadata.md ? @horacioh @Darking360 @nucliweb

**Comment by jorgeruvalcaba** [comment]
@jorgeepc @SerotoninaAbad @meyruiz @rodrigobustamante you're all assigned!

**Comment by MeLlamoPablo** [comment]
Hi! Can I take `tutorial/authentication-tutorial.md`? @horacioh @Darking360 @nucliweb

**Comment by xmartinezpujol** [comment]
#87 ready here.

I'll wait a bit for more work as I have 2 pending reviews. Good work everyone :clap:

**Comment by rodrigobustamante** [comment]
I finished #90 !

**Comment by meyruiz** [comment]
Finished #91. Can I take docs/sass.md ? @horacioh  @Darking360

**Comment by enBonnet** [comment]
`seo.md` done!

**Comment by SerotoninaAbad** [comment]
> May I take `docs/docs/creating-a-sitemap.md`? @horacioh @Darking360

creating-a-sitemap.md done! (Ready for Review PR #94)
May I take creating-a-local-plugin.md? @horacioh @Darking360

**Comment by horacioh** [comment]
# ⚠️ IMPORTANT ANNOUNCEMENT!! ⚠️ 

In order to organize the work better and have a little more structure, we (the Code Owners) make a decision of stop accepting contributions from all the files but only this ones right now. The other Issue will be there as a reference, but only one section at a time will be active. **In order to continue to the next block of docs, we need to finish the current one**

> **But you are reviewing all the translation pretty slow Horacio, what are you going to do about that?**

Good point <LOVELY_HUMAN>, you are right. right now we are only three code owners and we are not keeping up with all the contributions as fast as you want. That's why we are recruiting more reviewers now so we can work faster on the reviewing part 🎉 

You can go to [Tutorials Translation Progress](#97) to pick your next translation!.

Thanks and let's continue the good work!

**Comment by nutboltu** [comment]
@horacioh In order to get the actual percentage of finish work for http://is-gatsby-translated-yet.netlify.com, I am going to change the Title of this closed issue. Hope it won't affect a lot in your translation journey. :)
