### ISSUE TITLE
Typo on CONTRIBUTING.MD

### ISSUE THREAD

**Issue by enBonnet** [gatsbyjs/gatsby-es#58]
On line 11
Can see `Sbemos` must be `Sabemos`

**Comment by enBonnet** [comment]
@horacioh  @Darking360 can i take this case?

**Comment by enBonnet** [comment]
Same file on line 25 `exitamos` must be `evitamos`

**Comment by Darking360** [comment]
Hey, @enBonnet muchas gracias por notarlos, podrías abrir un PR con esos cambios y le podemos hacer merge? :heart:

**Comment by Darking360** [comment]
Resuelto en: https://github.com/gatsbyjs/gatsby-es/pull/59
